export function convertCodeISO2(countryName) {
  switch (countryName) {
    case '가나':
      return 'GH';

    default:
      break;
  }
}

export function convertCodeISO3(countryName) {
  switch (countryName) {
    case '가나':
      return 'GHA';
    case '가봉':
      return 'GAB';
    case '가이아나':
      return 'GUY';
    case '감비아':
      return 'GMB';
    case '건지':
      return 'GGY';
    case '과들루프':
      return 'GLP';
    case '과테말라':
      return 'GTM';
    case '괌':
      return 'GUM';
    case '교황청':
      return 'VAT';
    case '그레나다':
      return 'GRD';
    case '그리스':
      return 'GRC';
    case '그린란드':
      return 'GRL';
    case '기니':
      return 'GIN';
    case '기니비사우':
      return 'GNB';
    case '나미비아':
      return 'NAM';
    case '나우루':
      return 'NRU';
    case '나이지리아':
      return 'NGA';
    case '남수단':
      return 'SSD';
    case '남아프리카공화국':
      return 'ZAF';
    case '네덜란드':
      return 'NLD';
    case '네팔':
      return 'NPL';
    case '노르웨이':
      return 'NOR';
    case '뉴질랜드':
      return 'NZL';
    case '니우에':
      return 'NIU';
    case '니제르':
      return 'NER';
    case '니카라과':
      return 'NIC';
    case '대만':
      return 'TWN';
    case '덴마크':
      return 'DNK';
    case '도미니카':
    case '도미니카공화국':
      return 'DOM';
    case '도미니카연방':
      return 'DMA';
    case '독일':
      return 'DEU';
    case '동티모르':
      return 'TLS';
    case '라오스':
      return 'LAO';
    case '라이베리아':
      return 'LBR';
    case '라트비아':
      return 'LVA';
    case '러시아':
      return 'RUS';
    case '레바논':
      return 'LBN';
    case '레소토':
      return 'LSO';
    case '레위니옹':
      return 'REU';
    case '루마니아':
      return 'ROU';
    case '룩셈부르크':
      return 'LUX';
    case '르완다':
      return 'RWA';
    case '리비아':
      return 'LBY';
    case '리투아니아':
      return 'LTU';
    case '리히텐슈타인':
      return 'LIE';
    case '마다가스카르':
      return 'MDG';
    case '마르티니크':
      return 'MTQ';
    case '마셜제도':
      return 'MHL';
    case '마요트':
      return 'MYT';
    case '마이크로네시아':
      return 'FSM';
    case '마카오':
      return 'MAC';
    case '말라위':
      return 'MWI';
    case '말레이시아':
      return 'MYS';
    case '말리':
      return 'MLI';
    case '멕시코':
      return 'MEX';
    case '모나코':
      return 'MCO';
    case '모로코':
      return 'MAR';
    case '모리셔스':
      return 'MUS';
    case '모리타니아':
      return 'MRT';
    case '모잠비크':
      return 'MOZ';
    case '몬테네그로':
      return 'MNE';
    case '몬트세랫':
      return 'MSR';
    case '몰도바':
      return 'MDA';
    case '몰디브':
      return 'MDV';
    case '몰타':
      return 'MLT';
    case '몽골':
      return 'MNG';
    case '미얀마':
      return 'MMR';
    case '미국':
      return 'USA';
    case '바누아투':
      return 'VUT';
    case '바레인':
      return 'BHR';
    case '바베이도스':
      return 'BRB';
    case '바하마':
      return 'BHS';
    case '방글라데시':
      return 'BGD';
    case '버뮤다':
      return 'BMU';
    case '베냉':
      return 'BEN';
    case '베트남':
      return 'VNM';
    case '벨기에':
      return 'BEL';
    case '벨라루스':
      return 'BLR';
    case '벨리즈':
      return 'BLZ';
    case '보스니아헤르체고비나':
      return 'BIH';
    case '보츠와나':
      return 'BWA';
    case '볼리비아':
      return 'BOL';
    case '부룬디':
      return 'BDI';
    case '부르키나파소':
      return 'BFA';
    case '부탄':
      return 'BTN';
    case '마케도니아':
      return 'MKD';
    case '불가리아':
      return 'BGR';
    case '브라질':
      return 'BRA';
    case '브루나이':
      return 'BRN';
    case '사모아':
      return 'WSM';
    case '사우디아라비아':
      return 'SAU';
    case '사이프러스':
      return 'CYP';
    case '산마리노':
      return 'SMR';
    case '상투메프린시페':
      return 'STP';
    case '세네갈':
      return 'SEN';
    case '세르비아':
      return 'SRB';
    case '세이셸':
      return 'SYC';
    case '세인트루시아':
      return 'LCA';
    case '세인트빈센트그레나딘':
      return 'VCT';
    case '세인트키츠네비스':
      return 'KNA';
    case '소말리아':
      return 'SOM';
    case '솔로몬제도':
      return 'SLB';
    case '수단':
      return 'SDN';
    case '수리남':
      return 'SUR';
    case '스리랑카':
      return 'LKA';
    case '스웨덴':
      return 'SWE';
    case '스위스':
      return 'CHE';
    case '스페인':
      return 'ESP';
    case '슬로바키아':
      return 'SVK';
    case '슬로베니아':
      return 'SVN';
    case '시리아':
      return 'SYR';
    case '시에라리온':
      return 'SLE';
    case '싱가포르':
      return 'SGP';
    case '아랍에미리트':
      return 'ARE';
    case '아루바':
      return 'ABW';
    case '아르메니아':
      return 'ARM';
    case '아르헨티나':
      return 'ARG';
    case '아이슬란드':
      return 'ISL';
    case '아이티':
      return 'HTI';
    case '아일랜드':
      return 'IRL';
    case '아제르바이잔':
      return 'AZE';
    case '아프가니스탄':
      return 'AFG';
    case '안도라':
      return 'AND';
    case '알바니아':
      return 'ALB';
    case '알제리':
      return 'DZA';
    case '앙골라':
      return 'AGO';
    case '앤티가바부다':
      return 'ATG';
    case '에리트레아':
      return 'ERI';
    case '에스와티니':
      return 'SWZ';
    case '에스토니아':
      return 'EST';
    case '에콰도르':
      return 'ECU';
    case '에티오피아':
      return 'ETH';
    case '엘살바도르':
      return 'SLV';
    case '영국':
      return 'GBR';
    case '예멘':
      return 'YEM';
    case '오만':
      return 'OMN';
    case '오스트리아':
      return 'AUT';
    case '온두라스':
      return 'HND';
    case '요르단':
      return 'JOR';
    case '우간다':
      return 'UGA';
    case '우루과이':
      return 'URY';
    case '우즈베키스탄':
      return 'UZB';
    case '우크라이나':
      return 'UKR';
    case '이라크':
      return 'IRQ';
    case '이란':
      return 'IRN';
    case '이스라엘':
      return 'ISR';
    case '이집트':
      return 'EGY';
    case '이탈리아':
      return 'ITA';
    case '인도':
      return 'IND';
    case '인도네시아':
      return 'IDN';
    case '일본':
      return 'JPN';
    case '자메이카':
      return 'JAM';
    case '잠비아':
      return 'ZMB';
    case '적도기니':
      return 'GNQ';
    case '조지아':
      return 'GEO';
    case '중국':
      return 'CHN';
    case '중앙아프리카':
      return 'CAF';
    case '지부티':
      return 'DJI';
    case '지브롤터':
      return 'GIB';
    case '짐바브웨':
      return 'ZWE';
    case '차드':
      return 'TCD';
    case '체코':
      return 'CZE';
    case '칠레':
      return 'CHL';
    case '카메룬':
      return 'CMR';
    case '카보베르데':
      return 'CPV';
    case '카자흐스탄':
      return 'KAZ';
    case '카타르':
      return 'QAT';
    case '캄보디아':
      return 'KHM';
    case '캐나다':
      return 'CAN';
    case '케냐':
      return 'KEN';
    case '코모로':
      return 'COM';
    case '코소보':
      return 'XKX';
    case '코스타리카':
      return 'CRI';
    case '코트디부아르':
      return 'CIV';
    case '콜롬비아':
      return 'COL';
    case '콩고':
      return 'COD';
    case '쿠바':
      return 'CUB';
    case '쿠웨이트':
      return 'KWT';
    case '쿡제도':
      return 'COK';
    case '크로아티아':
      return 'HRV';
    case '키리바시':
      return 'KIR';
    case '타지키스탄':
      return 'TJK';
    case '탄자니아':
      return 'TZA';
    case '태국':
      return 'THA';
    case '토고':
      return 'TGO';
    case '통가':
      return 'TON';
    case '투르크메니스탄':
      return 'TKM';
    case '투발루':
      return 'TUV';
    case '튀니지':
      return 'TUN';
    case '튀르키예':
      return 'TUR';
    case '트리니다드토바고':
      return 'TTO';
    case '파나마':
      return 'PAN';
    case '파라과이':
      return 'PRY';
    case '파키스탄':
      return 'PAK';
    case '파푸아뉴기니':
      return 'PNG';
    case '팔라우':
      return 'PLW';
    case '팔레스타인':
      return 'PSE';
    case '페루':
      return 'PER';
    case '포르투갈':
      return 'PRT';
    case '폴란드':
      return 'POL';
    case '푸에르토리코':
      return 'PRI';
    case '프랑스':
      return 'FRA';
    case '피지':
      return 'FJI';
    case '핀란드':
      return 'FIN';
    case '필리핀':
      return 'PHL';
    case '헝가리':
      return 'HUN';
    case '호주':
      return 'AUS';
    case '홍콩':
      return 'HKG';

    default:
      break;
  }
}
