export function convertCodeISO2(countryName) {
  switch (countryName) {
    case `가나`:
      return `GH`;
    case `가봉`:
      return `GA`;
    case `가이아나`:
      return `GY`;
    case `감비아`:
      return `GM`;
    case `과테말라`:
      return `GT`;

    case `그레나다`:
      return `GD`;
    case `그리스`:
      return `GR`;

    case `기니`:
      return `GN`;
    case `기니비사우`:
      return `GW`;
    case `나미비아`:
      return `NA`;
    case `나우루`:
      return `NR`;
    case `나이지리아`:
      return `NG`;
    case `남수단`:
      return `SS`;
    case `남아프리카공화국`:
      return `ZA`;
    case `네덜란드`:
      return `NL`;
    case `네팔`:
      return `NP`;
    case `노르웨이`:
      return `NO`;
    case `뉴질랜드`:
      return `NZ`;
    case `니우에`:
      return `NU`;
    case `니제르`:
      return `NE`;
    case `니카라과`:
      return `NI`;
    case `대만`:
      return `TW`;
    case `덴마크`:
      return `DK`;

    case `도미니카공화국`:
      return `DO`;
    case `도미니카`:
      return `DO`;
    case `도미니카연방`:
      return `DM`;
    case `독일`:
      return `DE`;
    case `동티모르`:
      return `TL`;
    case `라오스`:
      return `LA`;
    case `라이베리아`:
      return `LR`;
    case `라트비아`:
      return `LV`;
    case `러시아`:
      return `RU`;
    case `레바논`:
      return `LB`;
    case `레소토`:
      return `LS`;
    case `레위니옹`:
      return `RE`;
    case `루마니아`:
      return `RO`;
    case `룩셈부르크`:
      return `LU`;
    case `르완다`:
      return `RW`;
    case `리비아`:
      return `LY`;
    case `리투아니아`:
      return `LT`;
    case `리히텐슈타인`:
      return `LI`;
    case `마다가스카르`:
      return `MG`;

    case `마셜제도`:
      return `MH`;

    case `마이크로네시아`:
      return `FM`;
    case `마카오`:
      return `MO`;
    case `말라위`:
      return `MW`;
    case `말레이시아`:
      return `MY`;
    case `말리`:
      return `ML`;
    case `멕시코`:
      return `MX`;
    case `모나코`:
      return `MC`;
    case `모로코`:
      return `MA`;
    case `모리셔스`:
      return `MU`;
    case `모리타니아`:
      return `MR`;
    case `모잠비크`:
      return `MZ`;
    case `몬테네그로`:
      return `ME`;
    case `몬트세랫`:
      return `MS`;
    case `몰도바`:
      return `MD`;
    case `몰디브`:
      return `MV`;
    case `몰타`:
      return `MT`;
    case `몽골`:
      return `MN`;
    case `미얀마`:
      return `MM`;
    case `미합중국`:
      return `US`;
    case `바누아투`:
      return `VU`;
    case `바레인`:
      return `BH`;
    case `바베이도스`:
      return `BB`;
    case `바하마`:
      return `BS`;
    case `방글라데시`:
      return `BD`;
    case `버뮤다`:
      return `BM`;
    case `베냉`:
      return `BJ`;
    case `베트남`:
      return `VN`;
    case `벨기에`:
      return `BE`;
    case `벨라루스`:
      return `BY`;
    case `벨리즈`:
      return `BZ`;
    case `보스니아헤르체고비나`:
      return `BA`;
    case `보츠와나`:
      return `BW`;
    case `볼리비아`:
      return `BO`;
    case `부룬디`:
      return `BI`;
    case `부르키나파소`:
      return `BF`;
    case `부탄`:
      return `BT`;
    case `마케도니아`:
      return `MK`;
    case `불가리아`:
      return `BG`;
    case `브라질`:
      return `BR`;
    case `브루나이`:
      return `BN`;
    case `사모아`:
      return `WS`;
    case `사우디아라비아`:
      return `SA`;
    case `사이프러스`:
      return `CY`;
    case `산마리노`:
      return `SM`;
    case `상투메프린시페`:
      return `ST`;
    case `세네갈`:
      return `SN`;
    case `세르비아`:
      return `RS`;
    case `세이셸`:
      return `SC`;
    case `세인트루시아`:
      return `LC`;
    case `세인트빈센트그레나딘`:
      return `VC`;
    case `세인트키츠네비스`:
      return `KN`;
    case `소말리아`:
      return `SO`;
    case `솔로몬제도`:
      return `SB`;
    case `수단`:
      return `SD`;
    case `수리남`:
      return `SR`;
    case `스리랑카`:
      return `LK`;
    case `스웨덴`:
      return `SE`;
    case `스위스`:
      return `CH`;
    case `스페인`:
      return `ES`;
    case `슬로바키아`:
      return `SK`;
    case `슬로베니아`:
      return `SI`;
    case `시리아`:
      return `SY`;
    case `시에라리온`:
      return `SL`;
    case `싱가포르`:
      return `SG`;
    case `아랍에미리트`:
      return `AE`;
    case `아루바`:
      return `AW`;
    case `아르메니아`:
      return `AM`;
    case `아르헨티나`:
      return `AR`;
    case `아이슬란드`:
      return `IS`;
    case `아이티`:
      return `HT`;
    case `아일랜드`:
      return `IE`;
    case `아제르바이잔`:
      return `AZ`;
    case `아프가니스탄`:
      return `AF`;
    case `안도라`:
      return `AD`;
    case `알바니아`:
      return `AL`;
    case `알제리`:
      return `DZ`;
    case `앙골라`:
      return `AO`;
    case `앤티가바부다`:
      return `AG`;
    case `에리트레아`:
      return `ER`;
    case `에스와티니`:
      return `SZ`;
    case `에스토니아`:
      return `EE`;
    case `에콰도르`:
      return `EC`;
    case `에티오피아`:
      return `ET`;
    case `엘살바도르`:
      return `SV`;
    case `영국`:
      return `GB`;
    case `예멘`:
      return `YE`;
    case `오만`:
      return `OM`;
    case `오스트리아`:
      return `AT`;
    case `온두라스`:
      return `HN`;
    case `요르단`:
      return `JO`;
    case `우간다`:
      return `UG`;
    case `우루과이`:
      return `UY`;
    case `우즈베키스탄`:
      return `UZ`;
    case `우크라이나`:
      return `UA`;
    case `이라크`:
      return `IQ`;
    case `이란`:
      return `IR`;
    case `이스라엘`:
      return `IL`;
    case `이집트`:
      return `EG`;
    case `이탈리아`:
      return `IT`;
    case `인도`:
      return `IN`;
    case `인도네시아`:
      return `ID`;
    case `일본`:
      return `JP`;
    case `자메이카`:
      return `JM`;
    case `잠비아`:
      return `ZM`;
    case `적도기니`:
      return `GQ`;
    case `조지아`:
      return `GE`;
    case `중국`:
      return `CN`;
    case `중앙아프리카`:
      return `CF`;
    case `지부티`:
      return `DJ`;
    case `지브롤터`:
      return `GI`;
    case `짐바브웨`:
      return `ZW`;
    case `차드`:
      return `TD`;
    case `체코`:
      return `CZ`;
    case `칠레`:
      return `CL`;
    case `카메룬`:
      return `CM`;
    case `카보베르데`:
      return `CV`;
    case `카자흐스탄`:
      return `KZ`;
    case `카타르`:
      return `QA`;
    case `캄보디아`:
      return `KH`;
    case `캐나다`:
      return `CA`;
    case `케냐`:
      return `KE`;
    case `코모로`:
      return `KM`;
    case `코소보`:
      return `XK`;
    case `코스타리카`:
      return `CR`;
    case `코트디부아르`:
      return `CI`;
    case `콜롬비아`:
      return `CO`;
    case `콩고`:
      return `CD`;
    case `쿠바`:
      return `CU`;
    case `쿠웨이트`:
      return `KW`;
    case `쿡제도`:
      return `CK`;
    case `크로아티아`:
      return `HR`;
    case `키리바시`:
      return `KI`;
    case `타지키스탄`:
      return `TJ`;
    case `탄자니아`:
      return `TZ`;
    case `태국`:
      return `TH`;
    case `토고`:
      return `TG`;
    case `통가`:
      return `TO`;
    case `투르크메니스탄`:
      return `TM`;
    case `투발루`:
      return `TV`;
    case `튀니지`:
      return `TN`;
    case `튀르키예`:
      return `TR`;
    case `트리니다드토바고`:
      return `TT`;
    case `파나마`:
      return `PA`;
    case `파라과이`:
      return `PY`;
    case `파키스탄`:
      return `PK`;
    case `파푸아뉴기니`:
      return `PG`;
    case `팔라우`:
      return `PW`;
    case `팔레스타인`:
      return `PS`;
    case `페루`:
      return `PE`;
    case `포르투갈`:
      return `PT`;
    case `폴란드`:
      return `PL`;
    case `푸에르토리코`:
      return `PR`;
    case `프랑스`:
      return `FR`;
    case `피지`:
      return `FJ`;
    case `핀란드`:
      return `FI`;
    case `필리핀`:
      return `PH`;
    case `헝가리`:
      return `HU`;
    case `호주`:
      return `AU`;
    case `홍콩`:
      return `HK`;

    default:
      break;
  }
}

export function convertCodeISO3(countryName) {
  switch (countryName) {
    case "가나":
      return "GHA";

    default:
      break;
  }
}
